[Unit]
After=remote-fs.target network-online.target
RequiresMountsFor=/mnt/nextcloud-data/publico
RequiresMountsFor=/mnt/nextcloud-data/usuarios
RequiresMountsFor=/mnt/nextcloud-data/laudos
RequiresMountsFor=/mnt/nextcloud-data/laudos-mega
RequiresMountsFor=/mnt/nextcloud-data/administrativo
