Match User nextcloud-sync
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AuthorizedKeysFile /etc/ssh/authorized_keys/%u
    ChrootDirectory /var/lib/samba-nextcloud-export
    ForceCommand internal-sftp -R -d /
    DisableForwarding yes
    PermitTTY no
    X11Forwarding no
